'use client';

import ReactMarkdown from 'react-markdown';

export default function IDPReport({ analysis, onReset }) {
  if (!analysis) return null;

  return (
    <div className="max-w-4xl mx-auto my-8">
      <div className="bg-white rounded-2xl shadow-xl overflow-hidden">
        {/* Header */}
        <div className="bg-gradient-to-r from-blue-600 to-indigo-700 p-8 text-white flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-bold">Your Individual Development Plan</h1>
            <p className="text-blue-100 text-sm opacity-90">Generated by AI Career Coach</p>
          </div>
          <button 
            onClick={onReset}
            className="px-4 py-2 bg-white/10 hover:bg-white/20 rounded-lg text-sm transition-all border border-white/30"
          >
            New Assessment
          </button>
        </div>

        {/* Content Area */}
        <div className="p-8 md:p-12">
          <div className="prose prose-blue max-w-none prose-headings:font-bold prose-h1:text-2xl prose-h2:text-xl prose-p:text-gray-600 prose-li:text-gray-600">
            {/* This component converts the AI's Markdown into clean HTML */}
            <ReactMarkdown>{analysis}</ReactMarkdown>
          </div>
        </div>

        {/* Footer Action */}
        <div className="bg-gray-50 p-6 border-t border-gray-100 text-center">
          <button 
            onClick={() => window.print()}
            className="text-blue-600 font-medium hover:text-blue-700 flex items-center gap-2 mx-auto"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            Save as PDF / Print
          </button>
        </div>
      </div>
    </div>
  );
}